---

- name: install user
  user:
    name: "{{ item }}"
    shell: "/bin/bash"
    state: present
    append: Yes
    groups: sudonopw
  with_items: "{{ githubusers }}"

- name: install ssh-keys from github
  authorized_key:
    user: "{{ item }}"
    state: present
    key: "https://github.com/{{ item }}.keys"
  with_items: "{{ githubusers }}"

